name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    - name: Cache Tools
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: tools
        key: ${{ runner.os }}-doc-tools-${{ hashFiles('recipe.cake') }}

    - name: Publishing documentaiton
      uses: cake-build/cake-action@5167c3f6a9e15c76f009de2acdfb9488552bc0b9 # v3
      with:
        script-path: recipe.cake
        target: Force-Publish-Documentation
        verbosity: Diagnostic
        cake-version: 1.3.0
